apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  # namespace: poc
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
    - name: jaeger-ui
      port: 80
      targetPort: 16686
